spring:
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lezione
    username: root
    password: root123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      fail_on_empty_beans: false
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect

